version: '3'
services:
  # RabbitMQ service
  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"  # RabbitMQ port for communication
      - "15672:15672"  # Management console web UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network

  # Anonymizer app service
  radiomics:
    build:
      context: .  # Current directory (where the Dockerfile is located)
    container_name: "radiomics"
    depends_on:
      - rabbitmq  # Wait for RabbitMQ to start before starting the anonymizer
    environment:
      - RABBITMQ_HOST=rabbitmq  # Service name of the RabbitMQ container
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    volumes:
      - ./config.yaml:/app/config.yaml  # Mount config.yaml into the container
      - ./radiomics_results:/app/radiomics_results

    networks:
      - app_network

networks:
  app_network:
    driver: bridge